dataset:
  prepared_dir: data/waxal_kik_tts
  train_filelist: filelists/train_single_speaker.txt
  dev_filelist: filelists/dev_single_speaker.txt
  test_filelist: filelists/test_single_speaker.txt
  speaker_map: speaker_map_single_speaker.json
  prep_stats: prep_stats.json

model:
  base_model: facebook/mms-tts-kik
  full_checkpoint_url: https://dl.fbaipublicfiles.com/mms/tts/full_model/kik.tar.gz

training:
  run_name: mms_kik_waxal_single_speaker
  output_dir: artifacts/mms_tts_kik_waxal_finetune
  batch_size: 16
  fp16_run: true
  learning_rate: 0.00005
  epochs: 10000
  eval_interval: 200
  log_interval: 50
  save_interval: 1000
  seed: 42

hub:
  repo_id: kihahu/mms-tts-kik-waxal-v1
  upload_patterns:
    - vits/logs/**
    - generated_config/**
    - bootstrap_summary.json
